gText_SetClock_WokeMeUp::
	.string "………………………………………………\n"
	.string "………………………………………………\p"
	.string "Zzz… Hm? Quoi…?\n"
	.string "Tu m'as réveillé!\p"
	.string "Mais quelle heure est-il?$"

gText_Oak_Welcome:: @ 82C897B
	.string "Bonjour! Désolé de l'attente!\p"
	.string "Bienvenue dans le monde de\n"
	.string "{POKEMON}!\p"
	.string "Mon nom est CHEN.\p"
	.string "Mais on m'appelle le PROF. {POKEMON}.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Ce monde…$"

gText_Oak_Pokemon2::
	.string "…est peuplé de créatures\n"
	.string "appelées {POKEMON}.\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "Humains et {POKEMON} vivent en parfaite\n"
	.string "harmonie…\p"
	.string "Certains jouent avec les {POKEMON},\n"
	.string "d'autres font des combats avec eux.\p"
	.string "$"

gText_Oak_MainSpeech2::
	.string "Mais il reste beaucoup à apprendre\n"
	.string "sur nos amis les {POKEMON}.\p"
	.string "De nombreux mystères planent à leur\n"
	.string "sujet.\p"
	.string "Et c'est pourquoi j'étudie les\n"
	.string "{POKEMON} tous les jours.\p"
	.string "Mais assez parlé de moi.\n"
	.string "Dis m'en un peu plus sur toi!\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "Es-tu un garçon?\n"
	.string "Ou bien une fille?$"

gText_Oak_WhatsYourName::
	.string "Heu… C'est quoi ton nom?\p"
	.string "$"

gText_Oak_SoItsPlayer::
	.string "D'accord…\n"
	.string "Donc ton nom est {PLAYER}.$"

gText_Oak_AreYouReady::
	.string "{PLAYER}, ta quête est sur le\n"
	.string "point de commencer.\p"
	.string "Joies et périls paveront ta route…\p"
	.string "Un monde de rêve, de dangers et de\n"
	.string "{POKEMON} t'attend!\n"
	.string "En avant!$"